[build]	
    command = "npm run build && npm run start"
    publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/_next/static"
  to = "/static/splat"
  status = 301
  force = true